import torch

a = torch.arange(20)
a = a.reshape((4,5))
print(a)
# b, c = torch.max(a, dim=1)
# print(b)
# print(c)
idx = torch.argmax(a)
print(idx)
a = torch.tensor([5])
b = torch.tensor([2])
c = (a/b).long()
print(c)
print(int(5/2))

# a = torch.tensor([0,1,2,3,4,5])
# # a = a.reshape((2,3))
# indies = torch.nonzero(a>=2)
# print(indies)
# print(a[a>=2])
# # print(a[a>=2].shape)
a = torch.tensor([5,4,3,2,1])
b = torch.argsort(a, descending=True)
print(b)